name: jsaddle-run CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
     - uses: DeterminateSystems/nix-installer-action@main
     - uses: actions/checkout@v3.5.3
     - uses: cachix/install-nix-action@v25
       with:
         nix_path: nixpkgs=channel:nixpkgs-unstable
     - name: Cancel Previous Runs
       uses: styfle/cancel-workflow-action@0.9.1
       with:
         access_token: ${{ github.token }}
     - uses: cachix/cachix-action@v16
       with:
         name: haskell-miso-cachix
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

     - name: Nix channel update
       run: nix-channel --update

     - name: Build
       run: nix-build
